/*
Problem statement

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

package main

import (
	"fmt"
	"log"
	"os"
	"strconv"
)

func findfib(x int) int {

	if x == 1 || x == 2 {
		return x
	} else {
		m := findfib(x - 1)
		n := findfib(x - 2)
		return (m + n)
	}
}

func main() {

	arg, err := strconv.Atoi(os.Args[1])

	if err != nil {
		log.Fatal(err)
	}

	total := 0

	idx := 1
	for {
		j := findfib(idx)
		if j%2 == 0 {
			total += j
		}
		if j > arg {
			break
		}
		idx++
	}

	fmt.Println(total)

}
